### ISSUE TITLE
Jarm crashes Minecraft

### ISSUE THREAD

**Issue by ghost** [NicosaurusRex99/JARMGit#15]
I've got a problem Jarm crashes the game, at the start I was thinking this happened because of other mods but nope still the same thing
Minecraft version 1.12.2
I am using last forge version 
forge-1.12.2-14.23.5.2838
Just another Ruby mod version is jarm-1.12.2.22
Using Java 8

**Comment by NicosaurusRex99** [comment]
Can i please have a crash log

**Comment by ghost** [comment]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 7/8/19 2:58 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.entity.passive.EntitySheep cannot be cast to net.minecraft.entity.player.EntityPlayer
	at naturix.jarm.events.EventArmorSet.onLivingHurtEvent(EventArmorSet.java:80)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_EventArmorSet_onLivingHurtEvent_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:603)
	at net.minecraft.entity.EntityLivingBase.func_70665_d(EntityLivingBase.java:1410)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:66)
	at net.minecraft.entity.passive.EntityWolf.func_70652_k(EntityWolf.java:353)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.passive.EntityWolf.func_70636_d(EntityWolf.java:212)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.EntityWolf.func_70071_h_(EntityWolf.java:230)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at naturix.jarm.events.EventArmorSet.onLivingHurtEvent(EventArmorSet.java:80)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_EventArmorSet_onLivingHurtEvent_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:603)
	at net.minecraft.entity.EntityLivingBase.func_70665_d(EntityLivingBase.java:1410)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:66)
	at net.minecraft.entity.passive.EntityWolf.func_70652_k(EntityWolf.java:353)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.passive.EntityWolf.func_70636_d(EntityWolf.java:212)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.EntityWolf.func_70071_h_(EntityWolf.java:230)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: minecraft:wolf (net.minecraft.entity.passive.EntityWolf)
	Entity ID: 71
	Entity Name: Wolf
	Entity's Exact location: 80.02, 63.00, 184.42
	Entity's Block location: World: (80,63,184), Chunk: (at 0,3,8 in 5,11; contains blocks 80,0,176 to 95,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.09, -0.08, 0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Hillionliat'/674, l='New World', x=81.50, y=67.00, z=251.50]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 3725663627403168438
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (84,64,248), Chunk: (at 4,4,8 in 5,15; contains blocks 80,0,240 to 95,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 29 game time, 29 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 159349 (now: false), thunder time: 45178 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 159758896 bytes (152 MB) / 539701248 bytes (514 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | jarm      | 1.12.2.22    | jarm-1.12.2.22.jar            | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Hillionliat'/674, l='New World', x=81.50, y=67.00, z=251.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[crash-2019-07-08_14.58.54-server.txt](https://github.com/NicosaurusRex99/JARMGit/files/3368680/crash-2019-07-08_14.58.54-server.txt)

**Comment by ghost** [comment]
Hello?

**Comment by NicosaurusRex99** [comment]
yeah i was asleep.
Testing the fix now

**Comment by NicosaurusRex99** [comment]
Fixed in a124571
